### ISSUE TITLE
Demo locally error

### ISSUE THREAD

**Issue by solidsea98** [mbzuai-oryx/GeoChat#10]
Greetings,

Thank you very much for open-sourcing this outstanding work!

I run the demo locally using the instructions in [LoRA.md](https://github.com/mbzuai-oryx/GeoChat/blob/main/docs/LoRA.md). But I'm experiencing bugs, when I select the image and enter the question, I get an error.
![1709120138126](https://github.com/mbzuai-oryx/GeoChat/assets/31641542/b3931dc3-bfdf-4de1-9356-01c8c49959ff)

AttributeError: 'NoneType' object has no attribute 'image_mean'
![1709120163169](https://github.com/mbzuai-oryx/GeoChat/assets/31641542/df28d8a6-3ac5-4428-9574-9049607715f3)

**Comment by SunShineAwayD** [comment]
how to solve?

**Comment by sheke123** [comment]
same question

**Comment by Jack-bo1220** [comment]
same question

**Comment by PrashantSukkumar2** [comment]
I have the same question, can  anyone help?

**Comment by vietvo89** [comment]
The error is the result of the incorrect `model_name` extracted from the `model_path` you provided. To understand, please read the code https://github.com/mbzuai-oryx/GeoChat/blob/main/geochat/mm_utils.py#L80. If `geochat` is not in the `model_name`, then `image_processor = None` and you get the error due to no `image_process.image_mean`. You can read the code https://github.com/mbzuai-oryx/GeoChat/blob/main/geochat/model/builder.py#L127 and https://github.com/mbzuai-oryx/GeoChat/blob/main/geochat/mm_utils.py#L48 to understand what I mean.

Original code: `model_name = get_model_name_from_path(args.model_path)`

My fix is to hardcode the model name: `model_name = 'geochat-7B'`. The second approach is to modify the function `get_model_name_from_path`.
