### ISSUE TITLE
Gradio Interface is not working

### ISSUE THREAD

**Issue by tejasri19** [mbzuai-oryx/GeoChat#3]
@KjAeRsTuIsK @msohaildanish

**Comment by KjAeRsTuIsK** [comment]
Hi, Thank you so much for your interest in our work. The demo should be working fine now. I am closing this issue for now.

**Comment by pwein-liveeo** [comment]
Hello @KjAeRsTuIsK,

the gradio interface is down again. 

Visiting https://be923c5b3785df5548.gradio.live/ leads to No interface is running right now. As you mentioned that it worked 16h ago for you [this issue](https://github.com/gradio-app/gradio/issues/3060) might be relevant for you where the devs mention that `gradio==3.19` should fix the issue.

Also want to point out [this comment](https://github.com/gradio-app/gradio/issues/3060#issuecomment-1440152939) raising that some UIs have pinned gradio versions, as that might be relevant for you.

I hope you can resolve the issue, since I'm really looking forward to checking out the demo. Great paper by the way!

**Comment by pwein-liveeo** [comment]
I just noticed that the demo works for the Demo button, which links to https://a0b04b1aabdf5c36b6.gradio.live/
but not for the Demo link in the Latest Updates section, which links to https://be923c5b3785df5548.gradio.live/

**Comment by KjAeRsTuIsK** [comment]
Hi @pwein-liveeo , the demo should be working fine now from both the links. Thank you for your patience.
